name: Workflow for Issues
on: 
  issues:
    types: opened
jobs:
  issue_workflow:
  runs-on: ubuntu-latest
  steps:
    - name: Output issue event information
      run: echo"${{toJson(github.event.issues)}}"